AWSTemplateFormatVersion: '2010-09-09'

Description: Example template for Redis Cluster custom resource
Parameters:
  CustomRedisClusterFunctionARN:
    Type: String
    Description: Custom resource Lambda function ARN

Resources:
    CustomRedisCluster:
      Type: 'Custom::CustomResource'
      Version: '1.0'
      Properties:
        ServiceToken:
          Ref: CustomRedisClusterFunctionARN
