AWSTemplateFormatVersion: '2010-09-09'
Description: Example template for Redis Cluster custom resource
Parameters:
  CustomRedisClusterFunctionARN:
    Type: String
    Description: The Lambda function ARN that deploys the cluster

Resources:
    CustomRedisCluster:
      Type: 'Custom::CustomResource'
      Version: '1.0'
      Properties:
        ServiceToken:
          Ref: CustomRedisClusterFunctionARN
